[platformio]
default_envs = native

[env:native]
platform = native
build_flags =
    -D SIMULATION_MODE=1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D SIMULATION_MODE=1